clc
clear 
close all

%% TIME
t = 0 : 0.001:1;

%% AMPLITUDES 

Am = 5;  % AMPLITUDE OF THE MODULATING SIGNAL
Ac = 10; % AMPLITUDE OF THE CARRIER SIGNAL

%% FREQUNCIES 

Fs = 1000;  % SAMPLING FREQUENCY
Fm = 5;     % MODULATING SIGNAL'S FREQUENCY
Fc = 20;    % CARRIER SIGNAL'S FREQUENCY

%% MODULATING SIGNAL ('M(t)') & CARRIER SIGNAL ('C(t)')

Mt = Am*cos(2*pi*Fm.*t);    % MODULATING SIGNAL
Ct = Ac*cos(2*pi*Fc.*t);    % CARRIER SIGNAL

%% FREQUENCY DEVIATION ('FREQDEV') & PHASE DEVIATION ('PHASEDEV')

FREQDEV = 0.5*Am;   % FREQUENCY DEVIATION
PHASEDEV = 0.1*Am;  % PHASE DEVIATION

%% MODULATED SIGNALS

FM = fmmod(Mt,Fc,Fs,FREQDEV);   % FM MODULATED SIGNAL
PM = pmmod(Mt,Fc,Fs,PHASEDEV);  % PM MODULATED SIGNAL

%% DEMODULATED SIGNAL (ORIGINAL SIGNAL)

FMDEMOD = fmdemod(FM,Fc,Fs,FREQDEV);    % FM DEMODULATED SIGNAL
PMDEMOD = pmdemod(PM,Fc,Fs,PHASEDEV);   % PM DEMODULATED SIGNAL

%% FIRGURES TO BE PLOTTED

%%FM MODULATED SIGNAL
figure
plot(t,FM,'b','linewidth',2);
xlabel('TIME')
ylabel('AMPLITUDES')
title('FM MODULATED SIGNAL')

%%PM MODULATED SIGNAL
figure
plot(t,PM,'b','linewidth',2);
xlabel('TIME')
ylabel('AMPLITUDES')
title('PM MODULATED SIGNAL')

%%FM DEMODULATED SIGNAL
figure
plot(t,FMDEMOD,'b','linewidth',2);
xlabel('TIME')
ylabel('AMPLITUDES')
title('FM DEMODULATED SIGNAL')

%%PM DEMODULATED SIGNAL
figure
plot(t,PMDEMOD,'b','linewidth',2);
xlabel('TIME')
ylabel('AMPLITUDES')
title('PM DEMODULATED SIGNAL')